#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : learn-python  # The title of the book. Will be placed in the left navbar.
author                      : Aviad Rozenhek  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo

repository:
  url                       : https://github.com/aviadr1/learn-python3  # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links


launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url : false
  
